

device: cuda:2
save_root: result/train_xyz_offset_theta_MSELoss

model:
  use_xavier_init: True
  ckpt: null
  output_dim: 6    # regress 6 parameters

train:

  epoch: 200


  train_data:
    root: [/media/datum/wangjl/data/active_vision_dataset/batch2_4.26, /media/datum/wangjl/data/active_vision_dataset/batch3_4.27]
    batch_size: 64
    imgsz: [224,224]
    shuffle: True
    num_workers: 2
    img_channel: rgbd  # rgb, depth, rgbd
    select_label_index: [0,1,2,3,4,5] # [offset_x, offset_y, offset_z, theta_x, theta_y, theta_z] select some values for regression
    transforms:
      ColorJitter:
        brightness: 0.5
        contrast: 0.3
        hue: 0.3
      ToTensor: null
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  val_data:
    root: [/media/datum/wangjl/data/active_vision_dataset/batch1_4.26]
    batch_size: 64
    imgsz: [224,224]
    img_channel: rgbd
    select_label_index: [0,1,2,3,4,5]
    shuffle: False
    num_workers: 2
    transforms:
      ToTensor: null
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

  optimizer:
    name: Adam
    params: 
      lr: 0.001

  
  scheduler:
    name: MultiStepLR
    params:
      milestones: [150, 180] 
      gamma: 0.1
  
  loss:
    name: MSELoss # L1Loss, MSELoss, SmoothL1Loss, HuberLoss
